import { Prisma } from '@prisma/client';
import { generateRefrigerators } from './utils';

export const locations = [
  {
    type: 'г',
    name: 'Минск',
    district: '',
    region: '',
    alias: 'minsk',
  },
  {
    type: 'г',
    name: 'Брест',
    district: '',
    region: 'Брестская',
    alias: 'brest',
  },
  {
    type: 'г',
    name: 'Витебск',
    district: '',
    region: 'Витебская',
    alias: 'vitebsk',
  },
  {
    type: 'г',
    name: 'Гомель',
    district: '',
    region: 'Гомельская',
    alias: 'gomel',
  },
  {
    type: 'г',
    name: 'Гродно',
    district: '',
    region: 'Гродненская',
    alias: 'grodno',
  },
  {
    type: 'г',
    name: 'Могилев',
    district: '',
    region: 'Могилевская',
    alias: 'mogilev',
  },
  {
    type: 'г',
    name: 'Барановичи',
    district: '',
    region: 'Брестская',
    alias: 'baranovichi',
  },
  {
    type: 'г',
    name: 'Бобруйск',
    district: '',
    region: 'Могилевская',
    alias: 'bobrujsk',
  },
  {
    type: 'г',
    name: 'Борисов',
    district: 'Борисовский',
    region: 'Минская',
    alias: 'borisov',
  },
  {
    type: 'г',
    name: 'Лида',
    district: 'Лидский',
    region: 'Гродненская',
    alias: 'lida',
  },
  {
    type: 'г',
    name: 'Мозырь',
    district: 'Мозырский',
    region: 'Гомельская',
    alias: 'mozyr',
  },
  {
    type: 'г',
    name: 'Молодечно',
    district: 'Молодечненский',
    region: 'Минская',
    alias: 'molodechno',
  },
  {
    type: 'г',
    name: 'Пинск',
    district: '',
    region: 'Брестская',
    alias: 'pinsk',
  },
  {
    type: 'г',
    name: 'Солигорск',
    district: 'Солигорский',
    region: 'Минская',
    alias: 'soligorsk',
  },
  {
    type: 'г',
    name: 'Новополоцк',
    district: '',
    region: 'Витебская',
    alias: 'novopolock',
  },
];

export const additionalServicesCategoriesNames = [
  'Перенавеска дверей',
  'Надежная защита',
  'Страхование',
];

export const initialReview = {
  advantages: 'Цена , вместимость',
  disadvantages: 'Шумность превышает 42дцб',
  summary: 'Шумность превышает 42дцб , у меня 46 , а ему только 2 месяца',
  rating: 4,
  comment:
    'Приносим извинения за доставленные неудобства. Благодаря Вашему отзыву, мы уточнили информацию о товаре у поставщика и исправили описание на сайте. Уровень шума 39 дБ. В результате вашего обращения, с Вами провели консультацию наши специалисты. Надеемся на понимание с Вашей стороны и на то, что у нас еще будет возможность произвести на Вас хорошее впечатление.',
};

export const refrigeratorImages: Prisma.ImageCreateManyProductInput[] = [
  {
    isMain: true,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_65bc97b9ca11d.jpeg',
  },
  {
    isMain: false,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_56c302b5e778c.jpeg',
  },
  {
    isMain: false,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_65bc97c131902.jpeg',
  },
  {
    isMain: false,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_65bc97f1c1251.jpeg',
  },
  {
    isMain: false,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_65bc97df5f0c3.jpeg',
  },
  {
    isMain: false,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_65bc97c9b6e99.jpeg',
  },
];

const largeBanners: Prisma.BannerCreateManyInput[] = [
  {
    image: '/images/superdiscounts.jpg',
    link: '/special_offers/superdiscounts',
    title: 'Распрода 10%',
    size: 'Large',
  },
  {
    image: '/images/couch.jpg',
    link: '/special_offers/couches',
    title: 'Мягкая мебель',
    size: 'Large',
  },
  {
    image: '/images/adgameBanner.jpg',
    link: '/company/news/8944',
    title: 'РИ 5',
    size: 'Large',
  },
  {
    image: '/images/KVI.jpg',
    link: '/special_offers/sale_goods',
    title: 'KVI 5 неделя ',
    size: 'Large',
  },
  {
    image: '/images/wow_sale.jpg',
    link: '/special_offers/wow_sale',
    title: 'Щедрые цены ',
    size: 'Large',
  },
  {
    image: '/images/tv_lg.jpg',
    link: '/tv/55ur78009ll_lg',
    title: 'Телевизор LG',
    size: 'Large',
  },
  {
    image: '/images/mothersday.jpg',
    link: '/special_offers/mothersday',
    title: 'День матери ',
    size: 'Large',
  },
  {
    image: '/images/installment21.jpg',
    link: '/special_offers/installment21',
    title: 'Дольки ',
    size: 'Large',
  },
  {
    image: '/images/construction_mixtures.jpg',
    link: '/special_offers/construction_mixtures',
    title: 'Строй. смеси',
    size: 'Large',
  },
  {
    image: '/images/mattresses.jpg',
    link: '/mattresses/?order%5Bpopularity%5D=desc&filter%5Bdiscount_type%5D%5B0%5D=present&filter%5Bsa%5D=&filter%5B122428%5D%5B0%5D=1134268',
    title: 'Матрасы ',
    size: 'Large',
  },
];

const bottomBanners: Prisma.BannerCreateManyInput[] = [
  {
    image: '/images/kitfort.png',
    link: '/special_offers/kitfort',
    title: 'Kitfort',
    description: 'фабрика новинок',
    size: 'Small',
  },
  {
    image: '/images/xiaomi.png',
    link: '/special_offers/xiaomi21',
    title: 'Xiaomi',
    description: 'топ продаж',
    size: 'Small',
  },
  {
    image: '/images/lg.png',
    link: '/special_offers/promo?discountTypes=superprice%2Cdiscount&producers=3',
    title: 'LG',
    description: 'лучшие предложения',
    size: 'Small',
  },
  {
    image: '/images/belgoods.png',
    link: '/special_offers/belgoods',
    title: 'Кредит «На родныя тавары» ',
    description: 'ставка 4%',
    size: 'Small',
  },
  {
    image: '/images/mio_tesoro.jpg',
    link: '/special_offers/promo?categories=7314&producers=12563',
    title: 'Mio Tesoro ',
    description: 'домашний текстиль',
    size: 'Small',
  },
  {
    image: '/images/calmer.jpg',
    link: '/special_offers/promo?producers=57245',
    title: 'Calmer ',
    description: 'массажеры',
    size: 'Small',
  },
];

export const banners: Prisma.BannerCreateManyInput[] = [
  ...largeBanners,
  ...bottomBanners,
];

export const products: Omit<Prisma.ProductCreateManyInput, 'producerId'>[] = [
  {
    name: 'Холодильник с морозильником ХМ 4208-000 ATLANT',
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/atlant_4208000_65bc97b9ca11d.jpeg',
    discountTypes: ['Discount', 'Sale'],
    isInStock: true,
    price: 794.7,
    oldPrice: 883.0,
    discount: 10,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4626-159 ND',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4626159nd_atlant_3de3742cb666c888fbb07714a90113f4.jpg',
    price: 1913,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Nordfrost NR 403 S',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/nr403s_nord_64f57d53380e2.jpeg',
    price: 640,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Indesit ITS 5180 NG',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/its5180ng_indesit_9028600_66a8a3aa8d26c.jpeg',
    price: 1499,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Centek CT-1700 (черный)',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/ct1700_centek_01_6515231938be8.jpeg',
    price: 450,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника ATLANT Х-1601-100',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/1601100_atlant_65f9905fc4501.jpg',
    price: 1087.5,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника Nordfrost RF 50 B',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/rf50b_nord_64ec3b4c536fc.jpeg',
    price: 420,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника Nordfrost RF 50 W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/rf50w_nord_64ec3d3ae4596.jpeg',
    price: 420,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Nordfrost NR 404 B',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/nr404b_nord_8977752_6628a68f7b5ff.jpeg',
    price: 719,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Indesit ITR 4160 E',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/itr4160e_indesit_607e617cc16d6.jpeg',
    price: 1249,
    oldPrice: 1479,
    discountTypes: ['Discount', 'Sale'],
    discount: 16,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko RCNK335K00W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/rcnk335k00w_beko_59c251eddd18c.jpeg',
    price: 1399,
    oldPrice: 1569,
    discountTypes: ['Discount', 'Superprice'],
    discount: 11,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT X-1602 + М-7606 N',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/x16027606n_atlant_5b4f0a91b508d.jpeg',
    price: 2800,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Centek CT-1700 (белый)',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/ct1700_centek_65151e3e4d910.jpeg',
    price: 460,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT МХМ 2835-08',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/283508_atlant_65bba792dd881.jpg',
    price: 979,
    oldPrice: 1058,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4624-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4624101_atlant_65f17fa3cf10c.jpg',
    price: 1556.64,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B3RCNK362HX',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/b3rcnk362hx_beko_6204081de987e.jpeg',
    price: 1639,
    oldPrice: 1949,
    discountTypes: ['Discount'],
    discount: 16,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Stinol STS 185 G',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/sts185g_stinol__9028606_665995e153db1.jpeg',
    price: 1069,
    oldPrice: 1119,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Indesit ITR 4180 W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/itr4180w_indesit_66a39e3926920.jpeg',
    price: 1289,
    oldPrice: 1499,
    discountTypes: ['Discount', 'Sale'],
    discount: 14,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4623-109-ND',
    isInStock: true,
    link: '/refrigerators/',
    preview:
    '/images/refrigerators/4623109nd_atlant_65c322dc4b7a6.jpg',
    price: 1700,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Indesit ITR 4180 E',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/itr4180e_indesit_63c91ad93e5c6.jpeg',
    price: 1299,
    oldPrice: 1539,
    discountTypes: ['Discount', 'Sale'],
    discount: 16,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT МХМ 2826-90',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/atlant_282690_56c337ed9d07f.jpg',
    price: 958,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником LG GC-B459SLCL',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/gcb459slcl_lg_0c4ac884d01c80edd21a6b4a7ee58866.jpg',
    price: 2099,
    oldPrice: 2650,
    discountTypes: ['Discount', 'Superprice'],
    discount: 21,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ-4613-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4613101_atlant_9027432_6646fb63f2a3a.jpg',
    price: 1142,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4619-100',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4619100_atlant_59525f196b585.jpg',
    price: 1170,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4009-022',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/atlant_4009022_65bbaf3834af9.jpg',
    price: 1038,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника ATLANT Х 1602-150',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/1602150_atlant_65f9a1575ae5b.jpg',
    price: 1321,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4624-149 ND',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4624149nd_atlant_65c330dfaeb1f.jpg',
    price: 1830,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B1RCSK332W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/b1rcsk332w_beko_9030342_664affbbd78d4.jpg',
    price: 1259,
    oldPrice: 1409,
    discountTypes: ['Discount', 'Superprice'],
    discount: 11,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ-3635-109',
    isInStock: true,
    link: '/refrigerators/',
    preview:
    '/images/refrigerators/3635109_atlant_9132465_6686446e78ed5.jpg',
    price: 988,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4021-000',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/atlant_xm4021000_65bc9050eb676.jpg',
    price: 1124,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником TECHNO FF2-55N BI IV',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/ff255nbiiv_techno__661d0749988b8.jpeg',
    price: 2540,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 6021-080',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/atlant_6021080_65c5ccc535e29.jpeg',
    price: 1321,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника Nordfrost NR 507 W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/nr507w_nord_64f821c42273d.jpeg',
    price: 620,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника Nordfrost NR 506 S',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/nr506s_nord_655afcbe9adcd.jpeg',
    price: 443.69,
    oldPrice: 42.18,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4626-181',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4626181_atlant_65f43bfdb588b.jpg',
    price: 1536.13,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Stinol STN 167',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/stn167_stinol__8821265_661f6770ce4af.jpg',
    price: 1090,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko RCSK270M20W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/rcsk270m20w_beko_6202ae92c79db.jpeg',
    price: 1079,
    oldPrice: 1139,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Centek CT-1749 NF Inox Inverter',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/ct1749nfinoxinverter_centek_653626ba7610d.jpg',
    price: 2999,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 6026-031',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/atlant_6026031_65f409787ea27.jpg',
    price: 1425,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B5RCNK363ZW',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/b5rcnk363zw_beko_6251d2f4abd4e.jpeg',
    price: 1889,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko RCSK250M00S',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/rcsk250m00s_beko_5a3a4a9825db7.jpeg',
    price: 1109,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4626-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4626101_atlant_65f3f7ee99217.jpg',
    price: 1374,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ-4612-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4612101_atlant_9047797_6654272d3e769.jpg',
    price: 1147,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4621-159-ND',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4621159nd_atlant_65c247cd32d36.jpg',
    price: 1822,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником LG GC-B509SQCL',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/gcb509sqcl_lg_f24f76fbd43777760342139d1fd155bd.jpg',
    price: 2700,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Nordfrost NRT 141 232',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/nrt141232_nord_64d0b124a5d86.jpeg',
    price: 995,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B3R0CNK332HX',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/b3r0cnk332hx_beko_9246986_f3f50c7397aa5ed011b4d96abfb3ff4a.jpg',
    price: 1495,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Stinol STS 185',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/sts185_stinol__66aa0129d2a4b.jpeg',
    price: 999,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4610-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4610101_atlant_9043056_66502ef72cfb4.jpg',
    price: 1111,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником LG GC-B509SBSM',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/gcb509sbsm_lg_8864849_66b095bf03fca.jpeg',
    price: 3659,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Indesit ITR 5180 E',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/itr5180e_indesit_60d4183f13e18.jpeg',
    price: 1613.06,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4424-049 ND',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4424049nd_atlant_65c0abd1085d0.jpg',
    price: 1773,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4611-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/4611101_atlant_9030546_664af38db710b.jpg',
    price: 1111,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником TECHNO EF1-16',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/ef116_techno__655b3d0046fc6.jpeg',
    price: 729,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B1RCSK251G',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/b1rcsk251g_beko_9260129_a012a57003e392b1a1298c664c6e7209.jpg',
    price: 998.73,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Nordfrost RF 90 W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/rf90w_nord_64ec45cc4d7b3.jpeg',
    price: 640,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B1RCSK362S',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/b1rcsk362s_beko_64aba5f0a3e63.jpeg',
    price: 1299,
    oldPrice: 1519,
    discountTypes: ['Discount', 'Superprice'],
    discount: 14,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B3R0CNK332HW',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/b3r0cnk332hw_beko_9080511_6667e9d296ceb.jpeg',
    price: 1469,
    oldPrice: 1769,
    discountTypes: ['Discount', 'Superprice'],
    discount: 17,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 6024-080',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/atlant_6024080_65c5d2dcd1e29.jpg',
    price: 1422,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника Maunfeld MFF 83W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      '/images/refrigerators/mff83w_maunfeld_5f156c1fcad5b.jpg',
    price: 749,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
];

export const refrigerators = generateRefrigerators(products.length);
