import { Prisma } from '@prisma/client';
import { generateRefrigerators } from './utils';

export const locations = [
  {
    type: 'г',
    name: 'Минск',
    district: '',
    region: '',
    alias: 'minsk',
  },
  {
    type: 'г',
    name: 'Брест',
    district: '',
    region: 'Брестская',
    alias: 'brest',
  },
  {
    type: 'г',
    name: 'Витебск',
    district: '',
    region: 'Витебская',
    alias: 'vitebsk',
  },
  {
    type: 'г',
    name: 'Гомель',
    district: '',
    region: 'Гомельская',
    alias: 'gomel',
  },
  {
    type: 'г',
    name: 'Гродно',
    district: '',
    region: 'Гродненская',
    alias: 'grodno',
  },
  {
    type: 'г',
    name: 'Могилев',
    district: '',
    region: 'Могилевская',
    alias: 'mogilev',
  },
  {
    type: 'г',
    name: 'Барановичи',
    district: '',
    region: 'Брестская',
    alias: 'baranovichi',
  },
  {
    type: 'г',
    name: 'Бобруйск',
    district: '',
    region: 'Могилевская',
    alias: 'bobrujsk',
  },
  {
    type: 'г',
    name: 'Борисов',
    district: 'Борисовский',
    region: 'Минская',
    alias: 'borisov',
  },
  {
    type: 'г',
    name: 'Лида',
    district: 'Лидский',
    region: 'Гродненская',
    alias: 'lida',
  },
  {
    type: 'г',
    name: 'Мозырь',
    district: 'Мозырский',
    region: 'Гомельская',
    alias: 'mozyr',
  },
  {
    type: 'г',
    name: 'Молодечно',
    district: 'Молодечненский',
    region: 'Минская',
    alias: 'molodechno',
  },
  {
    type: 'г',
    name: 'Пинск',
    district: '',
    region: 'Брестская',
    alias: 'pinsk',
  },
  {
    type: 'г',
    name: 'Солигорск',
    district: 'Солигорский',
    region: 'Минская',
    alias: 'soligorsk',
  },
  {
    type: 'г',
    name: 'Новополоцк',
    district: '',
    region: 'Витебская',
    alias: 'novopolock',
  },
];

export const additionalServicesCategoriesNames = [
  'Перенавеска дверей',
  'Надежная защита',
  'Страхование',
];

export const initialReview = {
  advantages: 'Цена , вместимость',
  disadvantages: 'Шумность превышает 42дцб',
  summary: 'Шумность превышает 42дцб , у меня 46 , а ему только 2 месяца',
  rating: 4,
  comment:
    'Приносим извинения за доставленные неудобства. Благодаря Вашему отзыву, мы уточнили информацию о товаре у поставщика и исправили описание на сайте. Уровень шума 39 дБ. В результате вашего обращения, с Вами провели консультацию наши специалисты. Надеемся на понимание с Вашей стороны и на то, что у нас еще будет возможность произвести на Вас хорошее впечатление.',
};

export const refrigeratorImages: Prisma.ImageCreateManyProductInput[] = [
  {
    isMain: true,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_65bc97b9ca11d.jpeg',
  },
  {
    isMain: false,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_56c302b5e778c.jpeg',
  },
  {
    isMain: false,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_65bc97c131902.jpeg',
  },
  {
    isMain: false,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_65bc97f1c1251.jpeg',
  },
  {
    isMain: false,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_65bc97df5f0c3.jpeg',
  },
  {
    isMain: false,
    url: 'https://cdn21vek.by/img/galleries/58/129/atlant_4208000_65bc97c9b6e99.jpeg',
  },
];

const largeBanners: Prisma.BannerCreateManyInput[] = [
  {
    image: '/images/superdiscounts.jpg',
    link: '/special_offers/superdiscounts',
    title: 'Распрода 10%',
    size: 'Large',
  },
  {
    image: '/images/couch.jpg',
    link: '/special_offers/couches',
    title: 'Мягкая мебель',
    size: 'Large',
  },
  {
    image: '/images/adgameBanner.jpg',
    link: '/company/news/8944',
    title: 'РИ 5',
    size: 'Large',
  },
  {
    image: '/images/KVI.jpg',
    link: '/special_offers/sale_goods',
    title: 'KVI 5 неделя ',
    size: 'Large',
  },
  {
    image: '/images/wow_sale.jpg',
    link: '/special_offers/wow_sale',
    title: 'Щедрые цены ',
    size: 'Large',
  },
  {
    image: '/images/tv_lg.jpg',
    link: '/tv/55ur78009ll_lg',
    title: 'Телевизор LG',
    size: 'Large',
  },
  {
    image: '/images/mothersday.jpg',
    link: '/special_offers/mothersday',
    title: 'День матери ',
    size: 'Large',
  },
  {
    image: '/images/installment21.jpg',
    link: '/special_offers/installment21',
    title: 'Дольки ',
    size: 'Large',
  },
  {
    image: '/images/construction_mixtures.jpg',
    link: '/special_offers/construction_mixtures',
    title: 'Строй. смеси',
    size: 'Large',
  },
  {
    image: '/images/mattresses.jpg',
    link: '/mattresses/?order%5Bpopularity%5D=desc&filter%5Bdiscount_type%5D%5B0%5D=present&filter%5Bsa%5D=&filter%5B122428%5D%5B0%5D=1134268',
    title: 'Матрасы ',
    size: 'Large',
  },
];

const bottomBanners: Prisma.BannerCreateManyInput[] = [
  {
    image: '/images/kitfort.png',
    link: '/special_offers/kitfort',
    title: 'Kitfort',
    description: 'фабрика новинок',
    size: 'Small',
  },
  {
    image: '/images/xiaomi.png',
    link: '/special_offers/xiaomi21',
    title: 'Xiaomi',
    description: 'топ продаж',
    size: 'Small',
  },
  {
    image: '/images/lg.png',
    link: '/special_offers/promo?discountTypes=superprice%2Cdiscount&producers=3',
    title: 'LG',
    description: 'лучшие предложения',
    size: 'Small',
  },
  {
    image: '/images/belgoods.png',
    link: '/special_offers/belgoods',
    title: 'Кредит «На родныя тавары» ',
    description: 'ставка 4%',
    size: 'Small',
  },
  {
    image: '/images/mio_tesoro.jpg',
    link: '/special_offers/promo?categories=7314&producers=12563',
    title: 'Mio Tesoro ',
    description: 'домашний текстиль',
    size: 'Small',
  },
  {
    image: '/images/calmer.jpg',
    link: '/special_offers/promo?producers=57245',
    title: 'Calmer ',
    description: 'массажеры',
    size: 'Small',
  },
];

export const banners: Prisma.BannerCreateManyInput[] = [
  ...largeBanners,
  ...bottomBanners,
];

export const products: Omit<Prisma.ProductCreateManyInput, 'producerId'>[] = [
  {
    name: 'Холодильник с морозильником ХМ 4208-000 ATLANT',
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/58/129/preview/atlant_4208000_65bc97b9ca11d.jpeg',
    discountTypes: ['Discount', 'Sale'],
    isInStock: true,
    price: 794.7,
    oldPrice: 883.0,
    discount: 10,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4626-159 ND',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/7350/133/preview/4626159nd_atlant_4f920dc8f2fbc6db97727b37b4aab449.png',
    price: 1913,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Nordfrost NR 403 S',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8511/846/preview/nr403s_nord_64f57d53380e2.jpeg',
    price: 640,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Indesit ITS 5180 NG',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9028/600/preview/its5180ng_indesit_9028600_66a8a3aa8d26c.jpeg',
    price: 1499,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Centek CT-1700 (черный)',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8563/671/preview/ct1700_centek_01_6515231938be8.jpeg',
    price: 450,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника ATLANT Х-1601-100',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/5915/271/preview/1601100_atlant_bf4ec16e5fd69b1084f8699bf212464b.png',
    price: 1087.5,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника Nordfrost RF 50 B',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8512/683/preview/rf50b_nord_64ec3b4c536fc.jpeg',
    price: 420,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника Nordfrost RF 50 W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8512/682/preview/rf50w_nord_64ec3d3ae4596.jpeg',
    price: 420,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Nordfrost NR 404 B',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8977/752/preview/nr404b_nord_8977752_6628a68f7b5ff.jpeg',
    price: 719,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Indesit ITR 4160 E',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/6388/882/preview/itr4160e_indesit_607e617cc16d6.jpeg',
    price: 1249,
    oldPrice: 1479,
    discountTypes: ['Discount', 'Sale'],
    discount: 16,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko RCNK335K00W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/476/322/preview/rcnk335k00w_beko_59c251eddd18c.jpeg',
    price: 1399,
    oldPrice: 1569,
    discountTypes: ['Discount', 'Superprice'],
    discount: 11,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT X-1602 + М-7606 N',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/640/147/preview/x16027606n_atlant_5b4f0a91b508d.jpeg',
    price: 2800,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Centek CT-1700 (белый)',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8563/670/preview/ct1700_centek_65151e3e4d910.jpeg',
    price: 460,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT МХМ 2835-08',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/95/201/preview/283508_atlant_f602684c9d47798e0d8b95af42f647bc.png',
    price: 979,
    oldPrice: 1058,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4624-101 NL',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/6488/538/preview/4624101nl_atlant_a4a1f7f1ac89fb299074ce95ab79a29f.png',
    price: 1556.64,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B3RCNK362HX',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/7247/777/preview/b3rcnk362hx_beko_6204081de987e.jpeg',
    price: 1639,
    oldPrice: 1949,
    discountTypes: ['Discount'],
    discount: 16,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Stinol STS 185 G',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9028/606/preview/sts185g_stinol__9028606_665995e153db1.jpeg',
    price: 1069,
    oldPrice: 1119,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Indesit ITR 4180 W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/7235/292/preview/itr4180w_indesit_66a39e3926920.jpeg',
    price: 1289,
    oldPrice: 1499,
    discountTypes: ['Discount', 'Sale'],
    discount: 14,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4623-109-ND',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/6384/212/preview/4623109nd_atlant_79278c2b27d92bc9c31f26cdee4ccfc6.png',
    price: 1700,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Indesit ITR 4180 E',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/6388/884/preview/itr4180e_indesit_63c91ad93e5c6.jpeg',
    price: 1299,
    oldPrice: 1539,
    discountTypes: ['Discount', 'Sale'],
    discount: 16,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT МХМ 2826-90',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/5/433/preview/atlant_282690_694e0ad54441b7f9d82d640d25483ff8.png',
    price: 958,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником LG GC-B459SLCL',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8507/519/preview/gcb459slcl_lg_0c4ac884d01c80edd21a6b4a7ee58866.jpg',
    price: 2099,
    oldPrice: 2650,
    discountTypes: ['Discount', 'Superprice'],
    discount: 21,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ-4613-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9027/432/preview/4613101_atlant_9027432_691b0d08c477a3fe277a623b9ce9f09f.png',
    price: 1142,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4621-141',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/653/552/preview/4621141_atlant_4db95642cf88e95a74f4047e4ccefd5b.png',
    price: 1340,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4619-100',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/461/712/preview/4619100_atlant_0ba73755bac43021ee00f5caffb44349.png',
    price: 1170,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4009-022',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/7/93/preview/atlant_4009022_13344ec2bbbf038406503b6e2e0a70fe.png',
    price: 1038,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника ATLANT Х 1602-150',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/7347/804/preview/1602150_atlant_008fcd8af1b2a734700d8d1d53a2bff1.png',
    price: 1321,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4624-149 ND',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/6368/407/preview/4624149nd_atlant_65c330dfaeb1f.jpeg',
    price: 1830,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B1RCSK332W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9030/342/preview/b1rcsk332w_beko_9030342_664affbbd78d4.jpeg',
    price: 1259,
    oldPrice: 1409,
    discountTypes: ['Discount', 'Superprice'],
    discount: 11,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ-3635-109',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9132/465/preview/3635109_atlant_9132465_f6f287a7b8a4fae6f00cff897a0fd65e.png',
    price: 988,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4021-000',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/46/87/preview/atlant_xm4021000_0387cd9fb0d73dee9cd3b469c4daa6a1.png',
    price: 1124,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником TECHNO FF2-55N BI IV',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8745/563/preview/ff255nbiiv_techno__661d0749988b8.jpeg',
    price: 2540,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 6021-080',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/13/939/preview/atlant_6021080_65c5ccc535e29.jpeg',
    price: 1321,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника Nordfrost NR 507 W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/7238/420/preview/nr507w_nord_64f821c42273d.jpeg',
    price: 620,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника Nordfrost NR 506 S',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8657/170/preview/nr506s_nord_655afcbe9adcd.jpeg',
    price: 443.69,
    oldPrice: 42.18,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4626-181',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/5996/911/preview/4626181_atlant_99b5d2f4f25609704774c87bfd0a62a5.png',
    price: 1536.13,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Stinol STN 167',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8821/265/preview/stn167_stinol__8821265_661f6770ce4af.jpeg',
    price: 1090,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko RCSK270M20W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/522/727/preview/rcsk270m20w_beko_6202ae92c79db.jpeg',
    price: 1079,
    oldPrice: 1139,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Centek CT-1749 NF Inox Inverter',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8590/24/preview/ct1749nfinoxinverter_centek_653626ba7610d.jpeg',
    price: 2999,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 6026-031',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/4/552/preview/atlant_6026031_9cd14fffc94f85ba6e005d7106885f34.png',
    price: 1425,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B5RCNK363ZW',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/7353/379/preview/b5rcnk363zw_beko_6251d2f4abd4e.jpeg',
    price: 1889,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko RCSK250M00S',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/476/162/preview/rcsk250m00s_beko_5a3a4a9825db7.jpeg',
    price: 1109,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4626-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/513/578/preview/4626101_atlant_39623a6e96e94e26dacef68bcdc0e216.png',
    price: 1374,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ-4612-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9047/797/preview/4612101_atlant_9047797_6c062f3d26a6701c417ddfa3b9af0283.png',
    price: 1147,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4621-159-ND',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/7347/856/preview/4621159nd_atlant_65c247cd32d36.jpeg',
    price: 1822,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником LG GC-B509SQCL',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8579/617/preview/gcb509sqcl_lg_f24f76fbd43777760342139d1fd155bd.jpg',
    price: 2700,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Nordfrost NRT 141 232',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8478/622/preview/nrt141232_nord_64d0b124a5d86.jpeg',
    price: 995,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B3R0CNK332HX',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9246/986/preview/b3r0cnk332hx_beko_9246986_f3f50c7397aa5ed011b4d96abfb3ff4a.jpg',
    price: 1495,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Stinol STS 185',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8285/584/preview/sts185_stinol__66aa0129d2a4b.jpeg',
    price: 999,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4610-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9043/56/preview/4610101_atlant_9043056_8721faea15c3d8e4c93c5cc9e38707de.png',
    price: 1111,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником LG GC-B509SBSM',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8864/849/preview/gcb509sbsm_lg_8864849_66b095bf03fca.jpeg',
    price: 3659,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Indesit ITR 5180 E',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/6388/892/preview/itr5180e_indesit_60d4183f13e18.jpeg',
    price: 1613.06,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4424-049 ND',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/517/621/preview/4424049nd_atlant_6f5d5093337c8e79b4666d00362dd57c.png',
    price: 1773,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 4611-101',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9030/546/preview/4611101_atlant_9030546_dbfbb9d33414af59d222162b304114b2.jpg',
    price: 1111,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником TECHNO EF1-16',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8646/988/preview/ef116_techno__655b3d0046fc6.jpeg',
    price: 729,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B1RCSK251G',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9260/129/preview/b1rcsk251g_beko_9260129_a012a57003e392b1a1298c664c6e7209.jpg',
    price: 998.73,
    oldPrice: 0,
    discountTypes: [],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Nordfrost RF 90 W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8512/684/preview/rf90w_nord_64ec45cc4d7b3.jpeg',
    price: 640,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B1RCSK362S',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/8305/902/preview/b1rcsk362s_beko_64aba5f0a3e63.jpeg',
    price: 1299,
    oldPrice: 1519,
    discountTypes: ['Discount', 'Superprice'],
    discount: 14,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником Beko B3R0CNK332HW',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/9080/511/preview/b3r0cnk332hw_beko_9080511_6667e9d296ceb.jpeg',
    price: 1469,
    oldPrice: 1769,
    discountTypes: ['Discount', 'Superprice'],
    discount: 17,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник с морозильником ATLANT ХМ 6024-080',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/10/12/preview/atlant_6024080_e51494c88a0454217badfe226f84def6.png',
    price: 1422,
    oldPrice: 0,
    discountTypes: ['Sale'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
  {
    name: 'Холодильник без морозильника Maunfeld MFF 83W',
    isInStock: true,
    link: '/refrigerators/',
    preview:
      'https://cdn21vek.by/img/galleries/6062/709/preview/mff83w_maunfeld_5f156c1fcad5b.jpeg',
    price: 749,
    oldPrice: 0,
    discountTypes: ['Superprice'],
    discount: 0,
    rating: 4,
    reviewsCount: 1,
    fourStarsCommentsCount: 1,
  },
];

export const refrigerators = generateRefrigerators(products.length);
